version: '3.4'
services:
  app1: &app
    build: .
    hostname: app1
    environment:
      NAME: "1"
    expose:
      - "8080"

  app2:
    <<: *app
    hostname: app2
    environment:
      NAME: "2"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
